pretrained_model_name_or_path: "/home/notebook/data/group/LowLevelLLM/models/diffusion_models/stable-diffusion-2-1-base"
output_dir: "./experiment/ControlNetSR"
root_folders: "/home/notebook/data/group/LowLevelLLM/DataSets/lsdir_ffhq10k"

enable_xformers_memory_efficient_attention: true
ram_ft_path: "preset/models/DAPE.pth"
mixed_precision: "fp16"
resolution: 512
learning_rate: 5e-5
train_batch_size: 4
gradient_accumulation_steps: 1
null_text_ratio: 0.5
dataloader_num_workers: 0
checkpointing_steps: 500

seed: null
revision: null
variant: null
tokenizer_name: null
cache_dir: null
num_train_epochs: 1000
max_train_steps: null
checkpoints_total_limit: null
resume_from_checkpoint: null
gradient_checkpointing: false
scale_lr: false
lr_scheduler: "constant"
lr_warmup_steps: 500
lr_num_cycles: 1
lr_power: 1.0
use_8bit_adam: false
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1e-08
max_grad_norm: 1.0
push_to_hub: false
hub_token: null
hub_model_id: null
logging_dir: "logs"
allow_tf32: false
report_to: "tensorboard"
dataset_name: null
dataset_config_name: null
train_data_dir: null
image_column: "image"
conditioning_image_column: "conditioning_image"
caption_column: "text"
max_train_samples: null
proportion_empty_prompts: 0
validation_prompt: null
validation_image: null
num_validation_images: 4
validation_steps: 1
tracker_project_name: "train_controlnet_SR"
